// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Mesh_Generation 0

int map_width;
int map_height;

int triangle_count;

RWStructuredBuffer<float3> _Vertex_Buffer;
RWStructuredBuffer<float2> _Triangle_Buffer;
RWStructuredBuffer<float3> _Normals_Buffer;

float3 surface_normal_from_indices(int index_a, int index_b, int index_c)
{
    float3 point_a = _Vertex_Buffer[index_a];
    float3 point_b = _Vertex_Buffer[index_b];
    float3 point_c = _Vertex_Buffer[index_c];

    float3 side_a_b = point_b - point_a;
    float3 side_a_c = point_c - point_a;
    
    return normalize(cross(side_a_b, side_a_c));
}

void make_normals(uint3 id)
{
        for (int i = 0; i < triangle_count; i++)
        {
            int normal_triangle_index = i * 3;

            int vertex_index_a = _Triangle_Buffer[normal_triangle_index];
        }

        const int triangle_index = (id.y * (map_width - 1) + id.x) * 6; // Base index for triangles
        int vertex_index_a = _Triangle_Buffer[triangle_index];
        int vertex_index_b = _Triangle_Buffer[triangle_index + 1];
        int vertex_index_c = _Triangle_Buffer[triangle_index + 2];

        float3 triangle_normal = surface_normal_from_indices(vertex_index_a, vertex_index_b, vertex_index_c);
        
        _Normals_Buffer[vertex_index_a] += normalize(triangle_normal);
        _Normals_Buffer[vertex_index_b] += normalize(triangle_normal);
        _Normals_Buffer[vertex_index_c] += normalize(triangle_normal);
    
}

[numthreads(8,8,1)]
void Mesh_Generation (uint3 id : SV_DispatchThreadID)
{
    make_normals(id);
}
