/*
 * Author: Rebecca Biebl
 * Creation Date: 
 * Description:
 * License: MIT Licence
 */

// Define kernel functions for the compute shader.
#pragma kernel Mesh_Generation 0

int map_width; // Width of the map
int map_height; // Height of the map

int triangle_count; // Total number of triangles

RWStructuredBuffer<float3> _Vertex_Buffer; // Buffer for storing vertex data
RWStructuredBuffer<float2> _Triangle_Buffer; // Buffer for storing triangle data
RWStructuredBuffer<float3> _Normals_Buffer; // Buffer for storing normal data

/// Calculates the surface normal of a triangle defined by three vertex indices.
/// @param index_a The index of the first vertex.
/// @param index_b The index of the second vertex.
/// @param index_c The index of the third vertex.
/// @return The calculated surface normal of the triangle.
float3 surface_normal_from_indices(int index_a, int index_b, int index_c)
{
    // Get the positions of the three vertices
    float3 point_a = _Vertex_Buffer[index_a];
    float3 point_b = _Vertex_Buffer[index_b];
    float3 point_c = _Vertex_Buffer[index_c];

    // Calculate two sides of the triangle
    float3 side_a_b = point_b - point_a;
    float3 side_a_c = point_c - point_a;

    // Calculate and return the normalized surface normal
    return normalize(cross(side_a_b, side_a_c));
}

/// Calculates the normals for the vertices of the generated mesh.
/// This function calculates the normals for the vertices based on the triangle data.
/// @param id The dispatch thread ID.
void make_normals(uint3 id)
{
    // Calculate normals for each triangle in the mesh
    for (int i = 0; i < triangle_count; i++)
    {
        // Calculate the index of the current triangle
        int normal_triangle_index = i * 3;

        // Get the index of the first vertex of the triangle
        int vertex_index_a = _Triangle_Buffer[normal_triangle_index];
    }

    // Calculate the base index for the current triangle
    const int triangle_index = (id.y * (map_width - 1) + id.x) * 6;

    // Get the indices of the vertices of the current triangle
    int vertex_index_a = _Triangle_Buffer[triangle_index];
    int vertex_index_b = _Triangle_Buffer[triangle_index + 1];
    int vertex_index_c = _Triangle_Buffer[triangle_index + 2];

    // Calculate the surface normal for the current triangle
    float3 triangle_normal = surface_normal_from_indices(vertex_index_a, vertex_index_b, vertex_index_c);

    // Update the normals of the vertices with the calculated normal
    _Normals_Buffer[vertex_index_a] += normalize(triangle_normal);
    _Normals_Buffer[vertex_index_b] += normalize(triangle_normal);
    _Normals_Buffer[vertex_index_c] += normalize(triangle_normal);
}

/*
 * Compute shader kernel function for generating mesh data for terrain.
 * @param id The unique identifier for the current thread.
 */
[numthreads(8,8,1)]
void Mesh_Generation(uint3 id : SV_DispatchThreadID)
{
    // Call function to calculate normals for the mesh
    make_normals(id);
}
