/*
* Author: Rebecca Biebl
 * Creation Date: 21-05-2024
 * Description: A script for managing mesh generation in Unity.
 * License: Licence
 */

// Define kernel functions for the compute shader.
#pragma kernel Noise_Generator 0

// Include the SimplexNoise2D shader for generating noise.
#include "Packages/jp.keijiro.noiseshader/Shader/SimplexNoise2D.hlsl"

// Unsigned integer variables for the dimensions of the noise map.
uint map_width; // Width of the noise map
uint map_height; // Height of the noise map

// Parameters for noise generation.
float seed_offset; // Offset for the noise seed
float noise_scale; // Scale of the noise
float noise_height; // Height factor for the noise
int octaves; // Number of noise octaves
float lacunarity; // Frequency multiplier for each octave
float persistence; // Amplitude multiplier for each octave

float max_terrain_height; // Maximum height of the terrain

float island_radius;

int noise_type;

// Read-write structured buffers for noise data and mesh information.
RWStructuredBuffer<float3> _Vertex_Buffer; // Stores the vertices of the mesh
RWStructuredBuffer<int> _Triangle_Buffer; // Stores the indices for mesh triangles

float3 noise(const float sample_x, const float sample_y)
{
        // Calculate UV coordinates for noise generation.
    const float2 uv = float2(sample_x, sample_y) / float2(map_width, map_height);

    // Generate Simplex noise and add it to the accumulated value.
    float3 value = SimplexNoise(uv);
    
    return value;
}

float3 fractional_brownian_motion(float2 xy)
{
    float sample_x = xy.x;
    float sample_y = xy.y;
    
    // Initialize the accumulated noise value to zero.
    float3 value = float3(0.0f, 0.0f, 0.0f);
    // Initialize the initial amplitude for noise generation.
    float amplitude = 1.0f;
    // Initialize the initial frequency for noise generation.
    float frequency = 1.0f;

    // Loop through the specified number of octaves to generate noise.
    for (int o = 0; o < octaves; o++)
    {
        // Calculate UV coordinates for noise generation.
        const float2 uv = float2(sample_x * frequency, sample_y * frequency) / float2(map_width, map_height);

        // Generate Simplex noise and add it to the accumulated value.
        value += amplitude * SimplexNoise(uv);

        // Increase the amplitude and frequency for the next octave to add more detail to the noise.
        amplitude *= persistence;
        frequency *= lacunarity;
    }
    return value;
}

float3 domain_warping(const float sample_x, const float sample_y)
{
    float2 p = float2(sample_x, sample_y);

    float2 q, r;
    
    q.x = fractional_brownian_motion(p + float2(0.0, 0.0)).y;
    q.y = fractional_brownian_motion(p + float2(5.2, 1.3)).y;

    // float3 value = fractional_brownian_motion(float2(fbm1, fbm2));

    r.x = fractional_brownian_motion(p + 4.0 * q + float2(1.7, 9.2)).y;
    r.y = fractional_brownian_motion(p + 4.0 * q + float2(8.3, 2.8)).y;
    
    float3 value = fractional_brownian_motion(p + 20.0 * r);

    return value;
}

float falloff(float x, float y, float island_radius)
{
    float gradient = 1;

    gradient /= (x * y) / (map_width * map_height) * (1 - (x / map_width)) * (1 - (y / map_height));
    // gradient -= 16;
    gradient /= island_radius;


    return gradient;
    
    // float2 position = float2(x, y);
    // float dist = length(position) / island_radius;
    // float gradient = 1.0f - dist * dist;
    // return /*clamp(*/gradient/*, 0.0f, 1.0f)*/; // Hier wird der Gradient direkt geklammert, um im Bereich von 0 bis 1 zu bleiben.
}

/// <summary>
/// Generates noise for each thread ID within the map dimensions.
/// </summary>
/// <param name="id">The thread ID.</param>
/// <returns>The generated noise value for the thread ID.</returns>
[numthreads(16, 16, 1)]
void Noise_Generator(uint3 id : SV_DispatchThreadID)
{
    // Ensure the thread ID is within the map dimensions.
    if (id.x >= map_width || id.y >= map_height)
    {
        return; // Exit early if out of bounds
    }

    // Check if the current thread is within the bounds of the noise map.
    if (id.y < map_height && id.x < map_width)
    {
        // Calculate the index of the vertex in the buffer.
        const int vertex_index = id.y * map_width + id.x;

        // Calculate the sample coordinates for noise generation.
        const float sample_x = (id.x + seed_offset) * noise_scale;
        const float sample_y = (id.y + seed_offset) * noise_scale;

        float3 value = float3(0.0f, 0.0f, 0.0f);
        
        if (noise_type == 0)
        {
            value = noise(sample_x, sample_y);
        }
        else if (noise_type == 1)
        {
            value = fractional_brownian_motion(float2(sample_x, sample_y));
        }
        else if (noise_type == 2)
        {
            value = domain_warping(sample_x, sample_y);
        }

        float height = value.y;

        // // // Apply the falloff map
        // float falloff_value = falloff((float)id.x, (float)id.y, island_radius); // Example distortionScale
        // height -= falloff_value;

        // Calculate the position of the vertex in world space.
        const float top_left_x = (map_width - 1) / -2.0f;
        const float top_left_z = (map_height - 1) / -2.0f;
        const float3 vertex = float3(top_left_x + id.x, height, top_left_z + id.y);

        // Store the vertex position in the vertex buffer.
        _Vertex_Buffer[vertex_index] = vertex;
    }

    // Generate triangles if within the map bounds minus one (to avoid out-of-bounds indices).
    if (id.y < map_height - 1 && id.x < map_width - 1)
    {
        const int index = (id.y * (map_width - 1) + id.x) * 6; // Base index for triangles

        const int vertex_index = id.y * map_width + id.x; // Base index for vertices

        // Store the indices for the two triangles that make up each grid cell.
        _Triangle_Buffer[index + 0] = vertex_index + 0;
        _Triangle_Buffer[index + 1] = vertex_index + map_width;
        _Triangle_Buffer[index + 2] = vertex_index + 1;

        _Triangle_Buffer[index + 3] = vertex_index + 1;
        _Triangle_Buffer[index + 4] = vertex_index + map_width;
        _Triangle_Buffer[index + 5] = vertex_index + map_width + 1;
    }
}
