/*
* Author: Rebecca Biebl
 * Creation Date: 21-05-2024
 * Description: A script for managing mesh generation in Unity.
 * License: Licence
 */

// Define kernel functions for the compute shader.
#pragma kernel Noise_Generator 0

// Include the SimplexNoise2D shader for generating noise.
#include "Packages/jp.keijiro.noiseshader/Shader/SimplexNoise2D.hlsl"

#define SQRT_2 1.41421356237 // Precomputed square root of 2

// Unsigned integer variables for the dimensions of the noise map.
uint map_width; // Width of the noise map
uint map_height; // Height of the noise map

// Parameters for noise generation.
float2 seed_offset; // Offset for the noise seed
float noise_scale; // Scale of the noise
float noise_height; // Height factor for the noise

// FBM
int octaves; // Number of noise octaves
float amplitude;
float frequency;
float persistence; // Amplitude multiplier for each octave
float lacunarity; // Frequency multiplier for each octave

// Domain Warping
int warp_steps;
float domain_warping_multiplicative;

float2 offset; // Offset for the noise

float max_terrain_height; // Maximum height of the terrain

int triangle_count;

int noise_type;

bool is_water;

// Read-write structured buffers for noise data and mesh information.
RWStructuredBuffer<float3> _Vertex_Buffer; // Stores the vertices of the mesh
RWStructuredBuffer<float2> _UV_Buffer;
RWStructuredBuffer<float3> _Normals_Buffer;
RWStructuredBuffer<int> _Triangle_Buffer; // Stores the indices for mesh triangles
RWStructuredBuffer<int> _Noise_Layer_Buffer;
RWStructuredBuffer<float2> _Noise_Layer_Offset_Vectors;
RWStructuredBuffer<float2> _Domain_Warping_Offset_Vectors;

// This function generates pseudo-random numbers using a commonly employed technique in shader programming.
// It uses a dot product and a sine function to create pseudo-random values efficiently.
// This method is widely found in shader tutorials, examples, and open-source projects.
// It represents general graphics programming knowledge rather than being sourced from a specific origin.
float rand(float2 uv)
{
    return frac(sin(dot(uv, float2(12.9898, 78.233))) * 43758.5453);
}

float random_between()
{
    float min = -100000;
    float max = 100000;

    // Verwenden Sie die aktuelle Zeit als Basis für die Zufallszahlengenerierung.
    // Die frac-Funktion gibt den fraktionären Teil der Zeit zurück, was zu einer stetig wechselnden Zahl führt.
    float rand = frac(sin(dot(float2(min, max), float2(12.9898, 78.233))) * 43758.5453);

    // Skalieren Sie die Zufallszahl, um sie in den gewünschten Bereich zu bringen.
    return min + rand * (max - min);
}

float3 noise(const float2 xy)
{
    // Calculate UV coordinates for noise generation.
    const float2 uv = xy / float2(map_width, map_height);

    // Generate Simplex noise and add it to the accumulated value.
    float3 value = SimplexNoise(uv);

    return value;
}

float billow(float value)
{
    value = abs(value);
    return value;
}

float ridge(float value)
{
    value = 1 - billow(value);
    return value;
}

float3 fractional_brownian_motion(float2 pos)
{
    float3 value = float3(0.0f, 0.0f, 0.0f);
    // Initialize the initial amplitude for noise generation.
    float amp = amplitude;
    // Initialize the initial frequency for noise generation.
    float freq = frequency;

    // Loop through the specified number of octaves to generate noise.
    for (int o = 0; o < octaves; o++)
    {
        float2 octave_offset = float2(random_between() + _Noise_Layer_Offset_Vectors[o].x,
                                      random_between() + _Noise_Layer_Offset_Vectors[o].y);

        // Calculate UV coordinates for noise generation.
        const float2 uv = pos * freq + octave_offset;

        // Generate Simplex noise and add it to the accumulated value.
        float3 noise_value = noise(uv);

        switch (_Noise_Layer_Buffer[o])
        {
        case 0: // Regular
            break;
        case 1:
            noise_value.y = billow(noise_value.y);
            break;
        case 2:
            noise_value.y = ridge(noise_value.y);
            break;
        }

        value += amp * noise_value;

        // Increase the amplitude and frequency for the next octave to add more detail to the noise.
        amp *= persistence;
        freq *= lacunarity;
    }

    return value;
}

float3 domain_warping(const float2 p)
{
    float2 r = float2(0.0f, 0.0f);

    for (int i = 0; i < warp_steps; i++)
    {
        float posX = fractional_brownian_motion(
            p + domain_warping_multiplicative * r + _Domain_Warping_Offset_Vectors[i]).y;
        float posY = fractional_brownian_motion(
            p + domain_warping_multiplicative * r + _Domain_Warping_Offset_Vectors[i + 1]).y;

        r = float2(posX, posY);
    }

    return fractional_brownian_motion(p + domain_warping_multiplicative * r);
}

void make_vertices(uint3 id, const float half_width, const float half_height)
{
    // Verify if the current thread's ID is within the bounds of the noise map dimensions.
    if (id.y < map_height && id.x < map_width)
    {
        // Compute the index of the vertex within the buffer.
        const int vertex_index = id.y * map_width + id.x;

        // Adjust the x and y coordinates for noise sampling based on the map's center.
        const float2 samples = ((float2(id.x + seed_offset.x, id.y + seed_offset.y) - float2(half_width, half_height)) *
            noise_scale);

        // Generate the noise value for the current vertex.
        float3 value = domain_warping(samples);

        // Determine the vertex's position in world space relative to the top-left corner of the map.
        const float top_left_x = (map_width - 1) / -2.0f;
        const float top_left_z = (map_height - 1) / -2.0f;
        const float3 vertex = float3(top_left_x + id.x, value.y, top_left_z + id.y);

        _Vertex_Buffer[vertex_index] = vertex;
    }
}

void make_uvs(uint3 id)
{
    // Verify if the current thread's ID is within the bounds of the noise map dimensions.
    if (id.y < map_height && id.x < map_width)
    {
        // Compute the index of the vertex within the buffer.
        const int uv_index = id.y * map_width + id.x;

        float2 uv = float2(id.x / (float)map_width, id.y / (float)map_height);

        _UV_Buffer[uv_index] = uv;
    }
}

void make_triangles(uint3 id)
{
    // Generate triangles if within the map bounds minus one (to avoid out-of-bounds indices).
    if (id.y < map_height - 1 && id.x < map_width - 1)
    {
        const int index = (id.y * (map_width - 1) + id.x) * 6; // Base index for triangles

        const int vertex_index = id.y * map_width + id.x; // Base index for vertices

        // Store the indices for the two triangles that make up each grid cell.
        _Triangle_Buffer[index + 0] = vertex_index + 0;
        _Triangle_Buffer[index + 1] = vertex_index + map_width;
        _Triangle_Buffer[index + 2] = vertex_index + 1;

        _Triangle_Buffer[index + 3] = vertex_index + 1;
        _Triangle_Buffer[index + 4] = vertex_index + map_width;
        _Triangle_Buffer[index + 5] = vertex_index + map_width + 1;
    }
}

/// <summary>
/// Generates noise for each thread ID within the map dimensions.
/// </summary>
/// <param name="id">The thread ID.</param>
/// <returns>The generated noise value for the thread ID.</returns>
[numthreads(16, 16, 1)]
void Noise_Generator(uint3 id : SV_DispatchThreadID)
{
    // // Calculate the maximum valid x and y coordinates based on the map dimensions.
    // uint max_id_x = map_width - 1;
    // uint max_id_y = map_height - 1;
    //
    // // Ensure the thread ID is within the map dimensions.
    // // This prevents out-of-bounds access to the map data.
    // if (id.x > max_id_x || id.y > max_id_y)
    // {
    //     return; // Exit early if out of bounds
    // }

    // Ensure the thread ID is within the map dimensions.
    if (id.x >= map_width || id.y >= map_height)
    {
        return; // Exit early if out of bounds
    }

    // Calculate half the width and height of the map to center the sampling around the middle.
    // This ensures that the noise generation is symmetrical and centered on the map.
    float half_width = map_width / 2.0f;
    float half_height = map_height / 2.0f;

    // Generate vertices for the terrain mesh using the current thread ID and the map dimensions.
    // The vertices represent the corners of the triangles that will form the terrain mesh.
    make_vertices(id, half_width, half_height);

    make_uvs(id);

    // Generate triangles for the terrain mesh using the previously generated vertices.
    // Each triangle represents a small section of the terrain surface.
    make_triangles(id);

    // if (is_water)
    // {
    //     const int vertex_index = id.y * map_width + id.x;
    //     
    //     // Calculate the wave movement
    //     float wave_movement = clamp(sin(_Vertex_Buffer[vertex_index].y * 100 + time), 0.0f, 1.0f); // Adjust the multiplier and time variable as needed
    //
    //     // Modify the original height with the wave movement
    //     _Vertex_Buffer[vertex_index].y *= wave_movement;
    // }
}
