/*
* Author: Rebecca Biebl
 * Creation Date: 21-05-2024
 * Description: A script for managing mesh generation in Unity.
 * License: Licence
 */

// Define kernel functions for the compute shader.
#pragma kernel Noise_Generator 0

// Include the SimplexNoise2D shader for generating noise.
#include "Packages/jp.keijiro.noiseshader/Shader/SimplexNoise2D.hlsl"

#define SQRT_2 1.41421356237 // Precomputed square root of 2

// Unsigned integer variables for the dimensions of the noise map.
uint map_width; // Width of the noise map
uint map_height; // Height of the noise map

// Parameters for noise generation.
float seed_offset; // Offset for the noise seed
float noise_scale; // Scale of the noise
float noise_height; // Height factor for the noise
int octaves; // Number of noise octaves
float lacunarity; // Frequency multiplier for each octave
float persistence; // Amplitude multiplier for each octave

float max_terrain_height; // Maximum height of the terrain

float island_radius;

int noise_type;

// Read-write structured buffers for noise data and mesh information.
RWStructuredBuffer<float3> _Vertex_Buffer; // Stores the vertices of the mesh
RWStructuredBuffer<int> _Triangle_Buffer; // Stores the indices for mesh triangles
RWStructuredBuffer<float3> _Falloff_Map_Buffer; // Stores the noise values for each vertex

float3 noise(const float2 xy)
{
    // Calculate UV coordinates for noise generation.
    const float2 uv = xy / float2(map_width, map_height);

    // Generate Simplex noise and add it to the accumulated value.
    float3 value = SimplexNoise(uv);

    return value;
}

float3 fractional_brownian_motion(float2 xy)
{
    // Initialize the accumulated noise value to zero.
    float3 value = float3(0.0f, 0.0f, 0.0f);
    // Initialize the initial amplitude for noise generation.
    float amplitude = 1.0f;
    // Initialize the initial frequency for noise generation.
    float frequency = 1.0f;

    // Loop through the specified number of octaves to generate noise.
    for (int o = 0; o < octaves; o++)
    {
        // Calculate UV coordinates for noise generation.
        const float2 uv = xy * frequency;

        // Generate Simplex noise and add it to the accumulated value.
        value += amplitude * /*abs*/(noise(uv));

        // Increase the amplitude and frequency for the next octave to add more detail to the noise.
        amplitude *= persistence;
        frequency *= lacunarity;
    }

    return value;
}

float3 domain_warping(const float2 xy)
{
    const float2 p = xy;

    float2 q, r;

    q.x = fractional_brownian_motion(p + float2(0.0, 0.0)).y;
    q.y = fractional_brownian_motion(p + float2(5.2, 1.3)).y;

    // float3 value = fractional_brownian_motion(float2(fbm1, fbm2));

    r.x = fractional_brownian_motion(p + 4.0 * q + float2(1.7, 9.2)).y;
    r.y = fractional_brownian_motion(p + 4.0 * q + float2(8.3, 2.8)).y;

    return fractional_brownian_motion(p + 4.0f * r);
}

/// <summary>
/// Evaluates a given value using a specific mathematical function.
/// This function is often used to generate falloff maps or other smooth transitions.
///
/// The formula used is:
///   f(value) = (value^a) / ( (value^a) + ((b - b * value)^a) )
///
/// where:
/// - a controls the sharpness of the transition
/// - b adjusts the range over which the transition occurs
///
/// This formula creates a smooth S-shaped curve, which is useful for blending and creating gradients.
///
/// </summary>
/// <param name="value">Input value, typically between 0 and 1.</param>
/// <returns>Transformed value, typically between 0 and 1, representing the falloff effect.</returns>
float evaluate(const float value)
{
    const float a = 3.0f; // Sharpness control parameter
    const float b = 2.2f; // Range adjustment parameter

    // Compute the numerator: value raised to the power of a
    const float numerator = pow(value, a);

    // Compute the denominator: the sum of the numerator and a scaled and raised complement of value
    const float denominator = numerator + pow(b - b * value, a);

    // Return the result of the formula
    return numerator / denominator;
}

void falloff(uint3 id)
{
    if (id.y < map_height && id.x < map_width)
    {
        const int vertex_index = id.y * map_width + id.x;

        // Calculate normalized vertex coordinates
        const float x = 2.0f * id.x / (float)map_width - 1.0f;
        const float y = 2.0f * id.y / (float)map_height - 1.0f;

        // const float value = max(abs(x), abs(y));
        
        // Apply a scale factor to make the circle smaller
        const float scaleFactor = 0.5f; // Adjust this value to make the circle smaller or larger

        float value = min(1.0f, (x * x + y * y) / (SQRT_2 * scaleFactor));
        
        _Falloff_Map_Buffer[vertex_index] = evaluate(value);
    }
}

float ridge_noise(const float y)
{
    float n = abs(y); // create creases
    n = 1 - n; // invert so creases are at top
    // n = n * n; // sharpen creases

    return n;
}

// function generateHeight(x, y) {
//   
//     let h = noise(x * frequency, y * frequency);
//   
//     // warp the noise
//     if (warped) {
//     
//         let pX = x + (noise((x + 20) * warpFrequency, (y)      * warpFrequency) - 0.5) * warpAmplitude;
//         let pY = y + (noise((x)      * warpFrequency, (y + 20) * warpFrequency) - 0.5) * warpAmplitude;
//     
//     
//         h = noise(pX * frequency, pY * frequency);
//     }
//   
//     // if generating an island discount the height
//     if (island) {
//     
//         let d = p5.Vector.dist(createVector(x, y), createVector(width / 2, height / 2));
//         d /= width / 2;
//         d = 1 - d;
//     
//         h *= d;
//     
//     }
//   
//     // subtract the threshold
//     h = max(0, h - threshold);
//     h /= (1 - threshold);
//   
//     return h;
// }

float3 make_noise(const int vertex_index, const float sample_x, const float sample_y, uint3 id)
{
    float3 value = float3(0.0f, 0.0f, 0.0f);

    if (noise_type == 0)
    {
        value = noise(float2(sample_x, sample_y));
    }
    else if (noise_type == 1)
    {
        value = fractional_brownian_motion(float2(sample_x, sample_y));
    }
    else if (noise_type == 2)
    {
        value = domain_warping(float2(sample_x, sample_y));
    }

    value.y -= _Falloff_Map_Buffer[vertex_index].y;

    return value;
}

void make_vertices(uint3 id)
{
    falloff(id);

    // Check if the current thread is within the bounds of the noise map.
    if (id.y < map_height && id.x < map_width)
    {
        // Calculate the index of the vertex in the buffer.
        const int vertex_index = id.y * map_width + id.x;

        // Calculate the sample coordinates for noise generation.
        const float sample_x = (id.x + seed_offset) * noise_scale;
        const float sample_y = (id.y + seed_offset) * noise_scale;

        float3 value = make_noise(vertex_index, sample_x, sample_y, id);

        // Calculate the position of the vertex in world space.
        const float top_left_x = (map_width - 1) / -2.0f;
        const float top_left_z = (map_height - 1) / -2.0f;
        const float3 vertex = float3(top_left_x + id.x, value.y, top_left_z + id.y);

        // Store the vertex position in the vertex buffer.
        _Vertex_Buffer[vertex_index] = vertex;
    }
}

void make_triangles(uint3 id)
{
    // Generate triangles if within the map bounds minus one (to avoid out-of-bounds indices).
    if (id.y < map_height - 1 && id.x < map_width - 1)
    {
        const int index = (id.y * (map_width - 1) + id.x) * 6; // Base index for triangles

        const int vertex_index = id.y * map_width + id.x; // Base index for vertices

        // Store the indices for the two triangles that make up each grid cell.
        _Triangle_Buffer[index + 0] = vertex_index + 0;
        _Triangle_Buffer[index + 1] = vertex_index + map_width;
        _Triangle_Buffer[index + 2] = vertex_index + 1;

        _Triangle_Buffer[index + 3] = vertex_index + 1;
        _Triangle_Buffer[index + 4] = vertex_index + map_width;
        _Triangle_Buffer[index + 5] = vertex_index + map_width + 1;
    }
}

/// <summary>
/// Generates noise for each thread ID within the map dimensions.
/// </summary>
/// <param name="id">The thread ID.</param>
/// <returns>The generated noise value for the thread ID.</returns>
[numthreads(16, 16, 1)]
void Noise_Generator(uint3 id : SV_DispatchThreadID)
{
    // Ensure the thread ID is within the map dimensions.
    if (id.x >= map_width || id.y >= map_height)
    {
        return; // Exit early if out of bounds
    }

    make_vertices(id);

    make_triangles(id);
}
