@startuml
actor User as U

U -> EnvGen : Start()

EnvGen -> EnvGen : Init()
EnvGen -> EnvGen : Generate()

EnvGen -> TerrGen : GenerateTerrain()

TerrGen -> TerrGen : GenerateNoiseAndMesh()

TerrGen -> NoiseMgr : GenerateNoiseParameters()

NoiseMgr -> NoiseMgr : GenerateNoise()

NoiseMgr -> NoiseGen : Noise_Generator()

NoiseMgr -> ValClampMgr : CompareHeightValues()

ValClampMgr -> ValClampMgr : ComputeLocalMinMax()
ValClampMgr -> ValClamp : Compute_Local_Min_Max()

ValClampMgr -> ValClampMgr : ComputeGlobalMinMax()
ValClampMgr -> ValClamp : Compute_Global_Min_Max()

ValClampMgr -> ValClampMgr : ClampValues()
ValClampMgr -> ValClamp : Clamp_Height_Values()

ValClampMgr -> ValClampMgr : ComputeLocalMinMax()
ValClampMgr -> ValClamp : Compute_Local_Min_Max()

ValClampMgr -> ValClampMgr : ComputeGlobalMinMax()
ValClampMgr -> ValClamp : Compute_Global_Min_Max()

TerrGen -> MeshMgr : CreateMesh()

TerrGen -> TerrGen : ApplyColourToMesh()
TerrGen -> ColGenMgr : ColourMesh()
ColGenMgr -> ColGen : ColourMesh()
    
TerrGen -> MeshMgr :  AdjustMeshHeight()

alt generateWater
    EnvGen -> TerrGen : GenerateTerrain()
    
    TerrGen -> TerrGen : GenerateNoiseAndMesh()
    
    TerrGen -> NoiseMgr : GenerateNoiseParameters()
    
    NoiseMgr -> NoiseMgr : GenerateNoise()
    
    NoiseMgr -> NoiseGen : Noise_Generator()
    
    NoiseMgr -> ValClampMgr : CompareHeightValues()
    
ValClampMgr -> ValClampMgr : ComputeLocalMinMax()
ValClampMgr -> ValClamp : Compute_Local_Min_Max()

ValClampMgr -> ValClampMgr : ComputeGlobalMinMax()
ValClampMgr -> ValClamp : Compute_Global_Min_Max()

ValClampMgr -> ValClampMgr : ClampValues()
ValClampMgr -> ValClamp : Clamp_Height_Values()

ValClampMgr -> ValClampMgr : ComputeLocalMinMax()
ValClampMgr -> ValClamp : Compute_Local_Min_Max()

ValClampMgr -> ValClampMgr : ComputeGlobalMinMax()
ValClampMgr -> ValClamp : Compute_Global_Min_Max()
    
    TerrGen -> MeshMgr : CreateMesh()
    
    TerrGen -> TerrGen : SetWaterPos()
else
end

legend
  == Abkürzungen ==
  EnvGen : EnvironmentGenerator
  TerrGen : TerrainGenerator
  NoiseMgr : NoiseGenerationManager
  ValClampMgr : ValueClampManager
  MeshMgr : MeshGenerationManager
  ColGenMgr : ColourGenerationManager
  NoiseGen : NoiseGeneration.compute
  ValClamp : ValueClamp.compute
  ColGen : ColourGeneration.compute
end legend

@enduml






