@startuml

!theme plain
skinparam linetype ortho
skinparam package {
  BackgroundColor LightSkyBlue
}

' Define components
rectangle ColourGradient
rectangle ComputeBufferManager
rectangle EnvironmentGenerator
rectangle GeneratorFunctions
rectangle NoiseLayer
rectangle NoiseLayerSettings
rectangle Shaders
rectangle TerrainColour
rectangle TerrainGenerator

' Define the groups/packages
package "TerrainGenerationManagers" {
    rectangle ColourGenerationManager as TGM_CG
    rectangle MeshGenerationManager as TGM_M
    rectangle NoiseGenerationManager as TGM_NGM
}

package "TerrainSettings" {
    rectangle GeneralSettings as TS_GS
    rectangle NoiseSettings as TS_NS
}

' Define relationships
TGM_NGM -[#3574f0,plain]->> ComputeBufferManager  
TGM_NGM -[#3574f0,plain]->> GeneratorFunctions    
TGM_NGM -[#3574f0,plain]->> Shaders                   
TGM_NGM -[#3574f0,plain]->> TerrainSettings   

ComputeBufferManager -[#3574f0,plain]->> TS_NS

EnvironmentGenerator -[#3574f0,plain]->> ColourGradient              
EnvironmentGenerator -[#3574f0,plain]->> ComputeBufferManager         
EnvironmentGenerator -[#5fad65,dotted]->> Shaders                   
EnvironmentGenerator -[#3574f0,plain]->> TerrainGenerationManagers 
EnvironmentGenerator -[#3574f0,plain]->> TerrainGenerator           
EnvironmentGenerator -[#3574f0,plain]->> TerrainSettings    

TerrainGenerator -[#3574f0,plain]->> Shaders                   
TerrainGenerator -[#3574f0,plain]->> TerrainGenerationManagers 
TerrainGenerator -[#3574f0,plain]->> TerrainSettings 

GeneratorFunctions -[#3574f0,plain]->> ComputeBufferManager      
GeneratorFunctions -[#3574f0,plain]->> Shaders      

TS_NS -[#5fad65,plain]-> NoiseLayerSettings   

NoiseLayerSettings -[#5fad65,plain]-> NoiseLayer  

ColourGradient -[#5fad65,plain]->> TerrainColour  

TGM_CG -[#3574f0,plain]->> ComputeBufferManager      
TGM_CG -[#3574f0,plain]->> TS_GS 

' Define legend
note right of EnvironmentGenerator
  <b>Legend:</b>
  <color:#3574f0> - Plain Line</color><br/>
  <color:#5fad65> - Dotted Line</color><br/>
end note

@enduml

@startuml
!theme plain
skinparam linetype ortho

' Define packages
package "Core Components" {
  [EnvironmentGenerator]
  [ComputeBufferManager]
  [TerrainGenerator]
  [GeneratorFunctions]
}

package "TerrainGenerationManagers" {
  [ColourGenerationManager]
  [MeshGenerationManager]
  [NoiseGenerationManager]
}

package "TerrainSettings" {
  [GeneralSettings]
  [NoiseSettings]
}

package "Shaders" {
  [NoiseGeneration]
  [ColourGeneration]
  [ValueClamp]
}

' Define relationships
[EnvironmentGenerator] --> [TerrainGenerationManagers]
[EnvironmentGenerator] --> [TerrainSettings]
[EnvironmentGenerator] --> [ComputeBufferManager]
[EnvironmentGenerator] --> [TerrainGenerator]
[EnvironmentGenerator] --> [ColourGradient]

[ComputeBufferManager] --> [NoiseSettings]

[TerrainGenerator] --> [TerrainGenerationManagers]
[TerrainGenerator] --> [TerrainSettings]
[TerrainGenerator] --> [Shaders]
[TerrainGenerator] --> [GeneratorFunctions]

[NoiseSettings] --> [NoiseLayerSettings]
[NoiseLayerSettings] --> [NoiseLayer]

[ColourGradient] --> [TerrainColour]

[TerrainGenerationManagers] --> [ComputeBufferManager]
[TerrainGenerationManagers] --> [GeneralSettings]

@enduml

@startuml


package "Compute Shaders" {
    [NoiseGeneration.compute]
    [ValueClamp.compute]
    [ColourGeneration.compute]
}

package "C# Scripts" {
    [EnvironmentGenerator]
    [NoiseGenerationManager]
    [ValueClampManager]
    [MeshGenerationManager]
    [ColourGenerationManager]
    [TerrainGenerator]
}

[EnvironmentGenerator] -down-> [NoiseGenerationManager] : verwaltet
[EnvironmentGenerator] -down-> [ValueClampManager] : verwaltet
[EnvironmentGenerator] -down-> [MeshGenerationManager] : verwaltet
[EnvironmentGenerator] -down-> [ColourGenerationManager] : verwaltet
[EnvironmentGenerator] -down-> [TerrainGenerator] : aufgerufen

[TerrainGenerator] -down-> [NoiseGenerationManager] : aufgerufen
[TerrainGenerator] -down-> [MeshGenerationManager] : aufgerufen
[TerrainGenerator] -down-> [ColourGenerationManager] : aufgerufen

[NoiseGenerationManager] -down-> [ValueClampManager] : aufgerufen

[NoiseGenerationManager] -down-> [NoiseGeneration.compute] : aufgerufen
[ValueClampManager] -down-> [ValueClamp.compute] : aufgerufen
[ColourGenerationManager] -down-> [ColourGeneration.compute] : aufgerufen

@enduml

@startuml
actor User

User -> EnvironmentGenerator : Start()

EnvironmentGenerator -> EnvironmentGenerator : Init()

EnvironmentGenerator -> TerrainGenerator : GenerateTerrain()

TerrainGenerator -> NoiseGenerationManager : GenerateNoiseParameters()
NoiseGenerationManager -> NoiseGeneration.compute : GenerateNoise()
NoiseGenerationManager -> ValueClampManager : CompareHeightValues()

ValueClampManager -> ValueClamp.compute : ComputeHeightValues()
note right of ValueClamp.compute
    - ComputeLocalMinMax()
    - ComputeGlobalMinMax()
    - ClampHeightValues()
end note

alt isWater = true
    TerrainGenerator -> TerrainGenerator : SetWaterPosition()
else
    TerrainGenerator -> ColourGenerationManager : ApplyColourToMesh()
    ColourGenerationManager -> ColourGeneration.compute : ColourMesh()
end

@enduml

@startuml
actor User as U

U -> EnvGen : Start()

EnvGen -> EnvGen : Init()
EnvGen -> EnvGen : Generate()

EnvGen -> TerrGen : GenerateTerrain()

TerrGen -> TerrGen : GenerateNoiseAndMesh()

TerrGen -> NoiseMgr : GenerateNoiseParameters()

NoiseMgr -> NoiseMgr : GenerateNoise()

NoiseMgr -> NoiseGen : Noise_Generator()

NoiseMgr -> ValClampMgr : CompareHeightValues()

ValClampMgr -> ValClampMgr : ComputeLocalMinMax()
ValClampMgr -> ValClamp : Compute_Local_Min_Max()

ValClampMgr -> ValClampMgr : ComputeGlobalMinMax()
ValClampMgr -> ValClamp : Compute_Global_Min_Max()

ValClampMgr -> ValClampMgr : ClampValues()
ValClampMgr -> ValClamp : Clamp_Height_Values()

ValClampMgr -> ValClampMgr : ComputeLocalMinMax()
ValClampMgr -> ValClamp : Compute_Local_Min_Max()

ValClampMgr -> ValClampMgr : ComputeGlobalMinMax()
ValClampMgr -> ValClamp : Compute_Global_Min_Max()

TerrGen -> MeshMgr : CreateMesh()

TerrGen -> TerrGen : ApplyColourToMesh()
TerrGen -> ColGenMgr : ColourMesh()
ColGenMgr -> ColGen : ColourMesh()
    
TerrGen -> MeshMgr :  AdjustMeshHeight()

alt generateWater
    EnvGen -> TerrGen : GenerateTerrain()
    
    TerrGen -> TerrGen : GenerateNoiseAndMesh()
    
    TerrGen -> NoiseMgr : GenerateNoiseParameters()
    
    NoiseMgr -> NoiseMgr : GenerateNoise()
    
    NoiseMgr -> NoiseGen : Noise_Generator()
    
    NoiseMgr -> ValClampMgr : CompareHeightValues()
    
ValClampMgr -> ValClampMgr : ComputeLocalMinMax()
ValClampMgr -> ValClamp : Compute_Local_Min_Max()

ValClampMgr -> ValClampMgr : ComputeGlobalMinMax()
ValClampMgr -> ValClamp : Compute_Global_Min_Max()

ValClampMgr -> ValClampMgr : ClampValues()
ValClampMgr -> ValClamp : Clamp_Height_Values()

ValClampMgr -> ValClampMgr : ComputeLocalMinMax()
ValClampMgr -> ValClamp : Compute_Local_Min_Max()

ValClampMgr -> ValClampMgr : ComputeGlobalMinMax()
ValClampMgr -> ValClamp : Compute_Global_Min_Max()
    
    TerrGen -> MeshMgr : CreateMesh()
    
    TerrGen -> TerrGen : SetWaterPos()
else
end

legend
  == Abkürzungen ==
  EnvGen : EnvironmentGenerator
  TerrGen : TerrainGenerator
  NoiseMgr : NoiseGenerationManager
  ValClampMgr : ValueClampManager
  MeshMgr : MeshGenerationManager
  ColGenMgr : ColourGenerationManager
  NoiseGen : NoiseGeneration.compute
  ValClamp : ValueClamp.compute
  ColGen : ColourGeneration.compute
end legend

@enduml


@startmindmap

<style>
mindmapDiagram {
  .yellow {
    BackgroundColor yellow
  }
  .funktional {
    BackgroundColor lightgreen
  }
  .rose {
    BackgroundColor #FFBBCC
  }
  .orange {
    BackgroundColor orange
  }
  .nicht_funktional {
    BackgroundColor lightblue
  }
}
</style>

* Anforderungen <<orange>>

** Funktional <<funktional>>

*** Terrain-Mesh-Generierung <<funktional>>
*** FBM-basierte Gelände-Generierung <<funktional>>
*** Unterstützung von Domain Warping <<funktional>>
*** Parametersteuerung / Settings <<funktional>>

** Nicht-funktional <<nicht_funktional>>

*** Effiziente Berechnung des Terrain-Meshes \nmittels Compute Shadern <<nicht_funktional>>

@endmindmap






