@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

rectangle ColourGenerationManager
rectangle ColourGradient
rectangle ComputeBufferManager
rectangle EnvironmentGenerator
rectangle GeneralSettings
rectangle GeneratorFunctions
rectangle MeshGenerationManager
rectangle NoiseGenerationManager
rectangle NoiseLayer
rectangle NoiseLayerSettings
rectangle NoiseSettings
rectangle Shaders
rectangle TerrainColour
rectangle TerrainGenerationManagers
rectangle TerrainGenerator
rectangle TerrainSettings

ColourGenerationManager    -[#3574f0,plain]->>  ComputeBufferManager      
ColourGenerationManager    -[#3574f0,plain]->>  GeneralSettings           
ColourGenerationManager    -[#3574f0,plain]->>  TerrainColour 

ColourGradient             -[#5fad65,dotted]->>  TerrainColour  

ComputeBufferManager       -[#955ae0,plain]->>  ComputeBufferManager      
ComputeBufferManager       -[#5fad65,dotted]->>  ComputeBufferManager      
ComputeBufferManager       -[#3574f0,plain]->>  NoiseSettings             
ComputeBufferManager       -[#3574f0,plain]->>  TerrainSettings    

EnvironmentGenerator       -[#3574f0,plain]->>  ColourGenerationManager   
EnvironmentGenerator       -[#3574f0,plain]->>  ColourGradient              
EnvironmentGenerator       -[#3574f0,plain]->>  ComputeBufferManager      
EnvironmentGenerator       -[#3574f0,plain]->>  GeneralSettings            
EnvironmentGenerator       -[#3574f0,plain]->>  MeshGenerationManager     
EnvironmentGenerator       -[#3574f0,plain]->>  NoiseGenerationManager    
EnvironmentGenerator       -[#3574f0,plain]->>  NoiseSettings              
EnvironmentGenerator       -[#5fad65,dotted]->>  Shaders                   
EnvironmentGenerator       -[#3574f0,plain]->>  TerrainGenerationManagers 
EnvironmentGenerator       -[#3574f0,plain]->>  TerrainGenerator           
EnvironmentGenerator       -[#3574f0,plain]->>  TerrainSettings    

GeneratorFunctions         -[#3574f0,plain]->>  ComputeBufferManager      
GeneratorFunctions         -[#3574f0,plain]->>  Shaders      

NoiseGenerationManager     -[#3574f0,plain]->>  ComputeBufferManager      
NoiseGenerationManager     -[#3574f0,plain]->>  GeneralSettings           
NoiseGenerationManager     -[#3574f0,plain]->>  GeneratorFunctions        
NoiseGenerationManager     -[#3574f0,plain]->>  NoiseLayerSettings        
NoiseGenerationManager     -[#3574f0,plain]->>  NoiseSettings             
NoiseGenerationManager     -[#3574f0,plain]->>  Shaders                   
NoiseGenerationManager     -[#3574f0,plain]->>  TerrainSettings   

TerrainGenerator           -[#3574f0,plain]->>  ColourGenerationManager   
TerrainGenerator           -[#3574f0,plain]->>  GeneralSettings           
TerrainGenerator           -[#3574f0,plain]->>  MeshGenerationManager     
TerrainGenerator           -[#3574f0,plain]->>  NoiseGenerationManager    
TerrainGenerator           -[#3574f0,plain]->>  Shaders                   
TerrainGenerator           -[#3574f0,plain]->>  TerrainGenerationManagers 
TerrainGenerator           -[#3574f0,plain]->>  TerrainSettings 

TerrainGenerationManagers  *-[#955ae0,plain]->>  ColourGenerationManager          
TerrainGenerationManagers  *-[#955ae0,plain]->>  MeshGenerationManager      
TerrainGenerationManagers  *-[#955ae0,plain]->>  NoiseGenerationManager  
         
TerrainSettings            *-[#5fad65,plain]->  GeneralSettings           
TerrainSettings            *-[#5fad65,plain]->  NoiseSettings   

NoiseSettings              *-[#5fad65,plain]->  NoiseLayerSettings   

NoiseLayerSettings         *-[#5fad65,plain]->  NoiseLayer  

' Define legend
note right of EnvironmentGenerator
  <b>Legend:</b>
  <color:#3574f0> - Plain Line</color><br/>
  <color:#5fad65> - Dotted Line</color><br/>
  <color:#955ae0> - Plain Line with Color</color><br/>
end note

@enduml

